owner: chris9091 
repo: Monitor 

sites:
  - name: Fleksa
    url: https://fleksa.com
  - name: Good Taste
    url: https://goodtaste.fleksa.de
  - name: My.fleksa
    url: https://my.fleksa.com
  - name: Good Taste
    url: https://goodtaste.fleksa.de/  
  - name: Cheesy Burger
    url: https://cheesyburger-walsrode.de/
  - name: Pizzeria AMO
    url: https://amopizzeria.de
  - name: Berlin aaoji
    url: https://berlin-aaoji.de
  - name: Gandhi pizza
    url: http://gandhipizzaservice.de 
  - name: Indian Flavour
    url: http://indianflavour.de 
  - name: NIDDA API
    url: https://my.fleksa.com/pyapi/shop/restaurant-nidda.de/index
    method: GET
  - name: Eatarian
    url: https://eatarian.com
    method: GET
  - name: Deli tadka
    url: https://www.delitadka.de/
    method: GET  
  - name: Kiranekidukaan
    url: https://www.kiranekidukaan.de/
    method: GET 
  - name: Kirana store
    url: https://kirana-store.de/admin/sessions/login
    method: GET 
  - name: Fleksa monitor test
    url: https://chris9091.github.io/Fleksa_monitor01/    
  - name: Restaurant Ajad
    url: https://ajadberlin.de/
  - name: Dhaba@49 - The taste of India
    url: https://akkisindisch-foodcorner.de/
  - name: Ganesha Palace Albstadt
    url: https://albstadt-ganeshapalace.de/
  - name: Restaurant Taj Mahal
    url: https://allensbach-tajmahal.de/   
  - name: Pizza La Fontana
    url: https://altdorflafontana.de/
    
status-website:
  baseUrl: /Monitor
  introTitle: "**Fleksa** "
  introMessage: Dashboard for monitoring fleksa websites.


