owner: chris9091 
repo: Monitor 

sites:
  - name: Fleksa
    url: https://fleksa.com
  - name: Good Taste
    url: https://goodtaste.fleksa.de/
  - name: My.fleksa
    url: https://my.fleksa.com/
  - name: Good Taste
    url: https://goodtaste.fleksa.de/  
  - name: Cheesy Burger
    url: https://cheesyburger-walsrode.de/
  - name: Pizzeria AMO
    url: https://amopizzeria.de/

status-website:
  baseUrl: /Monitor
  introTitle: "**Fleksa** "
  introMessage: Dashboard for monitoring fleksa websites.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/chris9091/Monitor

