owner: chris9091 
repo: Monitor 

sites:
  - name: Fleksa
    url: https://fleksa.com
  - name: Good Taste
    url: https://goodtaste.fleksa.de/
 

status-website:
  baseUrl: /Monitor
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: Fleka sites monitoring websites.
  footer: Fleksa Monitoring 2022
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/chris9091/Monitor

